"use client";

import { useTranslations } from "next-intl";
import { useState, useCallback, useMemo, useEffect, useRef } from "react";
import { ALL_GAMES, type GameEntry } from "@/components/playground/MiniGames";
import { type GameMeta, type GameCategory } from "@/components/playground/GameCard";
import AIOrHumanGame from "@/components/playground/AIOrHumanGame";

/* ─── Neon palette ─── */
const NEON = {
  cyan: "#00FFD1",
  green: "#00FF88",
  purple: "#A855F7",
  amber: "#FBBF24",
  red: "#EF4444",
};

/* ─── Category → tag labels & neon accent ─── */
const CATEGORY_TAG: Record<GameCategory, { label: string; color: string }> = {
  knowledge: { label: "NLP", color: NEON.cyan },
  quick: { label: "Logic", color: NEON.green },
  ethics: { label: "Ethics", color: NEON.amber },
  creative: { label: "Neural Networks", color: NEON.purple },
};

const DIFFICULTY_BADGE: Record<string, { label: string; color: string }> = {
  easy: { label: "EASY", color: NEON.green },
  medium: { label: "MED", color: NEON.amber },
  hard: { label: "HARD", color: NEON.red },
};

/* ─── CSS Animations ─── */
const PLAYGROUND_STYLES = `
@keyframes pg-blink { 0%,100% { opacity: 1; } 50% { opacity: 0; } }
@keyframes pg-typing { from { width: 0; } to { width: 100%; } }
@keyframes pg-scanline {
  0% { transform: translateY(-100%); }
  100% { transform: translateY(100vh); }
}
@keyframes pg-card-in {
  from { opacity: 0; transform: translateY(20px) scale(0.97); }
  to { opacity: 1; transform: translateY(0) scale(1); }
}
@keyframes pg-overlay-in { from { opacity: 0; } to { opacity: 1; } }
@keyframes pg-slide-up {
  from { opacity: 0; transform: translateY(40px); }
  to { opacity: 1; transform: translateY(0); }
}
@keyframes pg-glow-pulse {
  0%, 100% { box-shadow: 0 0 5px rgba(0,255,209,0.15), inset 0 1px 0 rgba(0,255,209,0.05); }
  50% { box-shadow: 0 0 20px rgba(0,255,209,0.25), inset 0 1px 0 rgba(0,255,209,0.1); }
}
@keyframes pg-float {
  0%, 100% { transform: translateY(0px); }
  50% { transform: translateY(-4px); }
}

.pg-blink { animation: pg-blink 1s step-end infinite; }
.pg-card-stagger { animation: pg-card-in 0.5s cubic-bezier(0.22, 1, 0.36, 1) both; }
.pg-overlay-enter { animation: pg-overlay-in 0.3s ease-out both; }
.pg-slide-up-enter { animation: pg-slide-up 0.4s cubic-bezier(0.22, 1, 0.36, 1) both; }

.pg-lab-card {
  transition: transform 0.3s ease, box-shadow 0.3s ease, border-color 0.3s ease;
}
.pg-lab-card:hover {
  transform: translateY(-3px);
  border-color: rgba(0,255,209,0.4);
  box-shadow: 0 0 25px rgba(0,255,209,0.15), 0 0 50px rgba(0,255,209,0.05);
}

.pg-dot-bg {
  background-image: radial-gradient(rgba(255,255,255,0.03) 1px, transparent 1px);
  background-size: 24px 24px;
}

.pg-featured-glow {
  animation: pg-glow-pulse 3s ease-in-out infinite;
}
`;

/* ─── Typing effect hook ─── */
function useTypingEffect(text: string, speed = 60) {
  const [displayed, setDisplayed] = useState("");
  const [done, setDone] = useState(false);

  useEffect(() => {
    setDisplayed("");
    setDone(false);
    let i = 0;
    const interval = setInterval(() => {
      i++;
      setDisplayed(text.slice(0, i));
      if (i >= text.length) {
        clearInterval(interval);
        setDone(true);
      }
    }, speed);
    return () => clearInterval(interval);
  }, [text, speed]);

  return { displayed, done };
}

/* ─── Featured Game Definition ─── */
const FEATURED_GAME: GameMeta = {
  id: "ai-or-human",
  name: "AI or Human?",
  desc: "Guess if text is written by a human or generated by AI. It's harder than you think!",
  icon: "🤖",
  component: AIOrHumanGame,
  difficulty: "medium",
  estimatedMinutes: 2,
  category: "knowledge",
};

function buildGameList(): GameMeta[] {
  const miniGames: GameMeta[] = ALL_GAMES.map((g) => ({
    id: g.id,
    name: g.name,
    desc: g.desc,
    icon: g.icon,
    component: g.component,
    difficulty: g.difficulty,
    estimatedMinutes: g.estimatedMinutes,
    category: g.category,
  }));
  return [FEATURED_GAME, ...miniGames];
}

/* ─── Terminal window title bar (macOS dots) ─── */
function TerminalTitleBar({ title, tag }: { title: string; tag?: { label: string; color: string } }) {
  return (
    <div className="flex items-center gap-3 px-4 py-2.5 border-b border-white/[0.06] bg-white/[0.02]">
      <div className="flex gap-1.5">
        <span className="w-2.5 h-2.5 rounded-full bg-[#FF5F57]" />
        <span className="w-2.5 h-2.5 rounded-full bg-[#FEBC2E]" />
        <span className="w-2.5 h-2.5 rounded-full bg-[#28C840]" />
      </div>
      <span className="font-mono text-[11px] text-gray-500 flex-1 truncate">{title}</span>
      {tag && (
        <span
          className="font-mono text-[9px] uppercase tracking-widest px-2 py-0.5 rounded border"
          style={{ color: tag.color, borderColor: `${tag.color}33` }}
        >
          {tag.label}
        </span>
      )}
    </div>
  );
}

/* ─── Filter tag pills ─── */
const ALL_CATEGORIES: Array<{ key: GameCategory | "all"; label: string; color: string }> = [
  { key: "all", label: "ALL", color: NEON.cyan },
  { key: "knowledge", label: "NLP", color: NEON.cyan },
  { key: "quick", label: "LOGIC", color: NEON.green },
  { key: "ethics", label: "ETHICS", color: NEON.amber },
  { key: "creative", label: "NEURAL_NET", color: NEON.purple },
];

/* ─── Main Page ─── */
export default function PlaygroundPage() {
  const t = useTranslations("playground");
  const [activeGame, setActiveGame] = useState<GameMeta | null>(null);
  const overlayRef = useRef<HTMLDivElement>(null);
  const [closing, setClosing] = useState(false);
  const [filter, setFilter] = useState<GameCategory | "all">("all");

  const { displayed: heroText, done: heroDone } = useTypingEffect("> Initializing AI Lab...", 50);

  const allGames = useMemo(() => buildGameList(), []);

  const filteredGames = useMemo(() => {
    const games = allGames.filter((g) => g.id !== FEATURED_GAME.id);
    if (filter === "all") return games;
    return games.filter((g) => g.category === filter);
  }, [allGames, filter]);

  const handlePlay = useCallback((game: GameMeta) => {
    setActiveGame(game);
    setClosing(false);
    window.scrollTo({ top: 0, behavior: "smooth" });
  }, []);

  const handleClose = useCallback(() => {
    setClosing(true);
    setTimeout(() => {
      setActiveGame(null);
      setClosing(false);
    }, 300);
  }, []);

  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.key === "Escape" && activeGame) handleClose();
    };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, [activeGame, handleClose]);

  /* ─── Active Game Overlay ─── */
  if (activeGame) {
    const GameComponent = activeGame.component;
    const diff = DIFFICULTY_BADGE[activeGame.difficulty];
    return (
      <>
        <style>{PLAYGROUND_STYLES}</style>
        <div
          ref={overlayRef}
          className={`fixed inset-0 z-50 flex items-end sm:items-center justify-center ${closing ? "" : "pg-overlay-enter"}`}
          style={{
            backgroundColor: "rgba(0,0,0,0.75)",
            backdropFilter: "blur(16px)",
            WebkitBackdropFilter: "blur(16px)",
            ...(closing ? { opacity: 0, transition: "opacity 0.3s ease" } : {}),
          }}
          onClick={(e) => { if (e.target === e.currentTarget) handleClose(); }}
        >
          <div
            className={`relative w-full max-w-4xl max-h-[90vh] overflow-auto rounded-t-xl sm:rounded-xl border shadow-2xl ${closing ? "" : "pg-slide-up-enter"}`}
            style={{
              backgroundColor: "#0d0d0d",
              borderColor: "rgba(0,255,209,0.15)",
              ...(closing ? { opacity: 0, transform: "translateY(40px)", transition: "all 0.3s ease" } : {}),
            }}
          >
            {/* Terminal header */}
            <div className="sticky top-0 z-10 flex items-center justify-between border-b bg-[#0d0d0d]/95 backdrop-blur-sm" style={{ borderColor: "rgba(255,255,255,0.06)" }}>
              <div className="flex items-center gap-3 px-5 py-3">
                <div className="flex gap-1.5">
                  <span className="w-2.5 h-2.5 rounded-full bg-[#FF5F57]" />
                  <span className="w-2.5 h-2.5 rounded-full bg-[#FEBC2E]" />
                  <span className="w-2.5 h-2.5 rounded-full bg-[#28C840]" />
                </div>
                <span className="text-2xl">{activeGame.icon}</span>
                <div>
                  <h2 className="text-sm font-mono font-bold text-gray-200">{activeGame.name}</h2>
                  <p className="text-[10px] text-gray-500 font-mono hidden sm:block">{activeGame.desc}</p>
                </div>
              </div>
              <div className="flex items-center gap-3 pr-4">
                {diff && (
                  <span className="font-mono text-[9px] uppercase tracking-widest px-2 py-0.5 rounded border" style={{ color: diff.color, borderColor: `${diff.color}33` }}>
                    {diff.label}
                  </span>
                )}
                <span className="text-[10px] text-gray-600 hidden sm:inline font-mono">ESC</span>
                <button
                  onClick={handleClose}
                  className="min-h-[32px] min-w-[32px] inline-flex items-center justify-center rounded-lg border border-white/10 text-gray-500 hover:text-gray-200 hover:border-white/20 transition-all text-sm font-mono"
                  aria-label="Close"
                >
                  ✕
                </button>
              </div>
            </div>

            {/* Game content */}
            <div className="p-5 sm:p-8">
              <GameComponent />
            </div>
          </div>
        </div>
      </>
    );
  }

  /* ─── Game Hub (Lab Lobby) ─── */
  return (
    <>
      <style>{PLAYGROUND_STYLES}</style>
      <div className="min-h-screen pg-dot-bg" style={{ backgroundColor: "#0a0a0a", color: "#e5e5e5" }}>
        <div className="max-w-5xl mx-auto px-4 sm:px-6 py-10 md:py-16">

          {/* ── Terminal Hero ── */}
          <div className="mb-10">
            <div className="inline-block rounded-lg border px-5 py-4 mb-4" style={{ borderColor: "rgba(0,255,209,0.15)", backgroundColor: "rgba(0,255,209,0.03)" }}>
              <p className="font-mono text-sm sm:text-base" style={{ color: NEON.cyan }}>
                {heroText}
                {!heroDone && <span className="pg-blink">▌</span>}
              </p>
            </div>
            <h1 className="text-3xl sm:text-4xl font-bold font-mono tracking-tight mb-2">
              <span style={{ color: NEON.green }}>AI</span>{" "}
              <span className="text-gray-200">Experiment Lab</span>
            </h1>
            <p className="text-sm text-gray-500 font-mono">
              {allGames.length} experiments loaded{" "}
              <span style={{ color: NEON.green }}>●</span>{" "}
              all systems operational
            </p>
          </div>

          {/* ── Featured Experiment ── */}
          <button
            onClick={() => handlePlay(FEATURED_GAME)}
            className="group relative w-full mb-8 rounded-xl border text-left cursor-pointer overflow-hidden pg-featured-glow"
            style={{ borderColor: `${NEON.cyan}25`, backgroundColor: "rgba(0,255,209,0.02)" }}
          >
            <TerminalTitleBar title="featured_experiment.exe" tag={{ label: "FEATURED", color: NEON.cyan }} />
            <div className="px-5 py-5 sm:px-6 sm:py-6 flex items-center gap-5">
              <span className="text-4xl sm:text-5xl shrink-0" style={{ animation: "pg-float 3s ease-in-out infinite" }}>{FEATURED_GAME.icon}</span>
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 mb-1">
                  <span className="font-mono text-[10px] uppercase tracking-widest" style={{ color: NEON.cyan }}>Featured Experiment</span>
                  <span className="font-mono text-[9px] uppercase tracking-widest px-1.5 py-0.5 rounded border" style={{ color: DIFFICULTY_BADGE[FEATURED_GAME.difficulty].color, borderColor: `${DIFFICULTY_BADGE[FEATURED_GAME.difficulty].color}33` }}>
                    {DIFFICULTY_BADGE[FEATURED_GAME.difficulty].label}
                  </span>
                </div>
                <h2 className="text-lg sm:text-xl font-mono font-bold text-gray-100 truncate">{FEATURED_GAME.name}</h2>
                <p className="text-sm text-gray-500 mt-0.5 line-clamp-1 font-mono">{FEATURED_GAME.desc}</p>
              </div>
              <div className="shrink-0 hidden sm:flex items-center gap-2 px-4 py-2 rounded-lg font-mono text-xs font-bold border transition-all group-hover:border-opacity-60"
                style={{ color: NEON.cyan, borderColor: `${NEON.cyan}40`, backgroundColor: `${NEON.cyan}08` }}>
                {"> RUN"}
              </div>
            </div>
          </button>

          {/* ── Category Filter ── */}
          <div className="flex flex-wrap gap-2 mb-6">
            {ALL_CATEGORIES.map(cat => (
              <button
                key={cat.key}
                onClick={() => setFilter(cat.key)}
                className="font-mono text-[11px] uppercase tracking-wider px-3 py-1.5 rounded-md border transition-all"
                style={{
                  color: filter === cat.key ? "#0a0a0a" : cat.color,
                  borderColor: filter === cat.key ? cat.color : `${cat.color}30`,
                  backgroundColor: filter === cat.key ? cat.color : "transparent",
                }}
              >
                {cat.label}
              </button>
            ))}
          </div>

          {/* ── Experiment Grid ── */}
          {filteredGames.length === 0 ? (
            <div className="text-center py-16">
              <p className="text-3xl mb-3 opacity-40">🔍</p>
              <p className="text-sm font-mono text-gray-600">{t("hub.noGamesFound")}</p>
            </div>
          ) : (
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
              {filteredGames.map((game, i) => {
                const diff = DIFFICULTY_BADGE[game.difficulty];
                const tag = CATEGORY_TAG[game.category];
                return (
                  <button
                    key={game.id}
                    onClick={() => handlePlay(game)}
                    className="pg-lab-card pg-card-stagger group relative rounded-xl border text-left cursor-pointer overflow-hidden"
                    style={{
                      animationDelay: `${i * 60}ms`,
                      borderColor: "rgba(255,255,255,0.06)",
                      backgroundColor: "#111111",
                    }}
                  >
                    {/* macOS title bar */}
                    <TerminalTitleBar title={`exp_${game.id.replace(/-/g, "_")}.sh`} tag={tag} />

                    <div className="px-4 py-4">
                      {/* Icon + badges row */}
                      <div className="flex items-start justify-between mb-3">
                        <span className="text-3xl">{game.icon}</span>
                        <span
                          className="font-mono text-[9px] uppercase tracking-widest px-1.5 py-0.5 rounded border"
                          style={{ color: diff.color, borderColor: `${diff.color}33` }}
                        >
                          {diff.label}
                        </span>
                      </div>

                      {/* Title */}
                      <h3 className="text-sm font-mono font-bold text-gray-200 mb-1 truncate group-hover:text-[#00FFD1] transition-colors">
                        {game.name}
                      </h3>
                      <p className="text-xs text-gray-500 font-mono line-clamp-2 leading-relaxed mb-3">
                        {game.desc}
                      </p>

                      {/* Footer */}
                      <div className="flex items-center justify-between pt-2 border-t border-white/[0.04]">
                        <span className="text-[10px] text-gray-600 font-mono tabular-nums">
                          ~{game.estimatedMinutes} min
                        </span>
                        <span className="text-[10px] font-mono font-bold opacity-0 group-hover:opacity-100 transition-opacity" style={{ color: NEON.cyan }}>
                          {">"} RUN →
                        </span>
                      </div>
                    </div>
                  </button>
                );
              })}
            </div>
          )}

          {/* Footer */}
          <div className="mt-12 text-center">
            <p className="text-[11px] font-mono text-gray-600">
              <span style={{ color: NEON.green }}>$</span> {t("footer")}
            </p>
          </div>
        </div>
      </div>
    </>
  );
}
