"use client";

import { useTranslations } from "next-intl";
import { ScrollReveal } from "@open-ai-school/ai-ui-library";
import { useState, useCallback, useMemo, useEffect, useRef } from "react";
import { ALL_GAMES, type GameEntry } from "@/components/playground/MiniGames";
import GameCard, { type GameMeta, type GameCategory } from "@/components/playground/GameCard";
import AIOrHumanGame from "@/components/playground/AIOrHumanGame";

/* ─── Category + Featured Game Definitions ─── */
const CATEGORIES: { id: GameCategory | "all"; label: string; icon: string }[] = [
  { id: "all", label: "allCategories", icon: "🎯" },
  { id: "knowledge", label: "categoryKnowledge", icon: "🧠" },
  { id: "quick", label: "categoryQuickGames", icon: "🎮" },
  { id: "ethics", label: "categoryEthics", icon: "⚖️" },
  { id: "creative", label: "categoryCreative", icon: "✍️" },
  { id: "tools", label: "categoryTools", icon: "🔧" },
];

const FEATURED_GAME: GameMeta = {
  id: "ai-or-human",
  name: "AI or Human?",
  desc: "Guess if text is written by a human or generated by AI. It's harder than you think!",
  icon: "🤖",
  component: AIOrHumanGame,
  difficulty: "medium",
  estimatedMinutes: 2,
  category: "knowledge",
};

/* ─── Sentinel / Tool Games from page.tsx originals (moved inline) ─── */
/* These are kept in the page as "tool" category items but loaded via overlay */

function buildGameList(): GameMeta[] {
  const featured: GameMeta = FEATURED_GAME;
  const miniGames: GameMeta[] = ALL_GAMES.map((g) => ({
    id: g.id,
    name: g.name,
    desc: g.desc,
    icon: g.icon,
    component: g.component,
    difficulty: g.difficulty,
    estimatedMinutes: g.estimatedMinutes,
    category: g.category,
  }));
  return [featured, ...miniGames];
}

/* ─── Main Page ─── */
export default function PlaygroundPage() {
  const t = useTranslations("playground");
  const [activeGame, setActiveGame] = useState<GameMeta | null>(null);
  const [category, setCategory] = useState<GameCategory | "all">("all");
  const [search, setSearch] = useState("");
  const overlayRef = useRef<HTMLDivElement>(null);

  const allGames = useMemo(() => buildGameList(), []);

  const filteredGames = useMemo(() => {
    let games = allGames;
    if (category !== "all") {
      games = games.filter((g) => g.category === category);
    }
    if (search.trim()) {
      const q = search.toLowerCase();
      games = games.filter(
        (g) => g.name.toLowerCase().includes(q) || g.desc.toLowerCase().includes(q)
      );
    }
    return games;
  }, [allGames, category, search]);

  const handlePlay = useCallback((game: GameMeta) => {
    setActiveGame(game);
    window.scrollTo({ top: 0, behavior: "smooth" });
  }, []);

  const handleClose = useCallback(() => {
    setActiveGame(null);
  }, []);

  // Escape key to close game
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.key === "Escape" && activeGame) handleClose();
    };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, [activeGame, handleClose]);

  /* ─── Active Game Overlay ─── */
  if (activeGame) {
    const GameComponent = activeGame.component;
    return (
      <div className="max-w-4xl mx-auto px-4 sm:px-6 py-8 md:py-16" ref={overlayRef}>
        {/* Back button */}
        <button
          onClick={handleClose}
          className="min-h-[40px] inline-flex items-center gap-2 px-4 py-2 mb-6 text-sm font-medium text-[var(--color-text-muted)] hover:text-[var(--color-text)] border border-[var(--color-border)] rounded-xl hover:border-[var(--color-primary)] transition-all"
        >
          {t("hub.backToHub")}
        </button>

        {/* Game container */}
        <div className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-bg-card)] overflow-hidden shadow-2xl shadow-black/10">
          {/* Game header */}
          <div className="px-5 sm:px-8 py-5 border-b border-[var(--color-border)] bg-gradient-to-r from-indigo-500/5 to-violet-500/5">
            <div className="flex items-center gap-3">
              <span className="text-3xl">{activeGame.icon}</span>
              <div>
                <h2 className="text-xl font-bold">{activeGame.name}</h2>
                <p className="text-sm text-[var(--color-text-muted)]">{activeGame.desc}</p>
              </div>
            </div>
          </div>

          {/* Game content */}
          <div className="p-5 sm:p-8">
            <GameComponent />
          </div>
        </div>
      </div>
    );
  }

  /* ─── Game Hub (Lobby) ─── */
  return (
    <div className="max-w-6xl mx-auto px-4 sm:px-6 py-12 md:py-20">
      {/* Hero */}
      <ScrollReveal animation="fade-up">
        <div className="relative mb-12 text-center">
          {/* Animated gradient background */}
          <div className="absolute inset-0 -z-10 overflow-hidden rounded-3xl">
            <div className="absolute inset-0 bg-gradient-to-br from-indigo-500/10 via-violet-500/5 to-fuchsia-500/10 animate-pulse" style={{ animationDuration: "4s" }} />
            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-96 h-96 bg-gradient-to-r from-violet-500/20 to-fuchsia-500/20 rounded-full blur-3xl" />
          </div>

          <div className="py-12 px-6">
            <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-gradient-to-r from-indigo-500/10 to-violet-500/10 border border-indigo-500/20 text-xs font-medium text-indigo-400 mb-4">
              <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09z" />
              </svg>
              {t("hub.badge")}
            </div>
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold mb-4 bg-gradient-to-r from-indigo-400 via-violet-400 to-fuchsia-400 bg-clip-text text-transparent">
              {t("hub.title")}
            </h1>
            <p className="text-base sm:text-lg text-[var(--color-text-muted)] max-w-2xl mx-auto leading-relaxed">
              {t("hub.subtitle")}
            </p>
            <p className="text-sm text-[var(--color-text-muted)] mt-3">
              🎮 {t("hub.gamesAvailable", { count: allGames.length })}
            </p>
          </div>
        </div>
      </ScrollReveal>

      {/* Search + Category Filter */}
      <ScrollReveal animation="fade-up">
        <div className="mb-8 space-y-4">
          {/* Search */}
          <div className="relative max-w-md mx-auto">
            <svg className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-[var(--color-text-muted)]" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z" />
            </svg>
            <input
              type="text"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              placeholder={t("hub.searchPlaceholder")}
              className="w-full min-h-[44px] pl-10 pr-4 py-2.5 rounded-xl bg-[var(--color-bg)] border border-[var(--color-border)] text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500/50 focus:border-indigo-500 transition-all"
            />
          </div>

          {/* Category tabs */}
          <div className="flex flex-wrap justify-center gap-2">
            {CATEGORIES.map((cat) => (
              <button
                key={cat.id}
                onClick={() => setCategory(cat.id)}
                className={`min-h-[36px] px-4 py-1.5 rounded-full text-sm font-medium transition-all ${
                  category === cat.id
                    ? "bg-indigo-500 text-white shadow-lg shadow-indigo-500/20"
                    : "bg-[var(--color-bg-section)] border border-[var(--color-border)] text-[var(--color-text-muted)] hover:border-indigo-400 hover:text-[var(--color-text)]"
                }`}
              >
                <span className="mr-1.5">{cat.icon}</span>
                {t(`hub.${cat.label}`)}
              </button>
            ))}
          </div>
        </div>
      </ScrollReveal>

      {/* Game Grid */}
      <ScrollReveal animation="fade-up">
        {filteredGames.length === 0 ? (
          <div className="text-center py-16 text-[var(--color-text-muted)]">
            <p className="text-4xl mb-3">🔍</p>
            <p className="text-sm">{t("hub.noGamesFound")}</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
            {filteredGames.map((game) => (
              <GameCard key={game.id} game={game} onPlay={handlePlay} />
            ))}
          </div>
        )}
      </ScrollReveal>

      {/* Footer */}
      <div className="mt-12 text-center">
        <p className="text-xs text-[var(--color-text-muted)]">
          {t("footer")}
        </p>
      </div>
    </div>
  );
}
